[package]
name = "ssl-sim-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "ssl-sim"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
ssl-sim-core = { path = "../ssl-sim-core" }
ssl-sim-net = { path = "../ssl-sim-net" }
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
